### ISSUE TITLE
Unsupported Dart SDK

### ISSUE THREAD

**Issue by CodingNowPls** [rscloura/Doldrums#19]
help me plz.  my problem is  Exception: Unsupported Dart SDK, snapshot hash: be7d304ff826e2dfac63538e227c3cc5

dart version : 2.8.4

this is error msg : 

D:\program\Python\Python39\Doldrums>python src/main.py  libapp.so output
Traceback (most recent call last):
  File "D:\program\Python\Python39\Doldrums\src\main.py", line 85, in <module>
    isolate = parseELF(args.file)
  File "D:\program\Python\Python39\Doldrums\src\main.py", line 26, in parseELF
    loadLibraries(blobs[0])
  File "D:\program\Python\Python39\Doldrums\src\main.py", line 54, in loadLibraries
    raise Exception('Unsupported Dart SDK, snapshot hash: ' + snapshotHash)
Exception: Unsupported Dart SDK, snapshot hash: be7d304ff826e2dfac63538e227c3cc5

**Comment by johdcmlaker2000** [comment]
have the same issue, only a different hash is given out

**Comment by unoexperto** [comment]
List of versions: https://github.com/mildsunrise/darter/blob/master/info/versions.md
