### ISSUE TITLE
Unsupported Dart version！

### ISSUE THREAD

**Issue by 12qwertyuiop** [rscloura/Doldrums#21]
E:\Doldrums\Doldrums-main\src>python main.py libapp.so output
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    isolate = parseELF(args.file)
  File "main.py", line 26, in parseELF
    loadLibraries(blobs[0])
  File "main.py", line 54, in loadLibraries
    raise Exception('Unsupported Dart SDK, snapshot hash: ' + snapshotHash)
Exception: Unsupported Dart SDK, snapshot hash: adb4292f3ec25074ca70abcd2d5c7251

**Comment by borski** [comment]
I have this same issue

**Comment by Gintamashiichan** [comment]
Same, outdated.

**Comment by stevejubx** [comment]
If you require reverse engineering for dart current version, I recommend using <a href="https://github.com/worawit/blutter">b(l)utter</a>

**Comment by Nux-xader** [comment]
> If you require reverse engineering for dart current version, I recommend using [b(l)utter](https://github.com/worawit/blutter)

the result isn't same with libapp.so in my case, i think it's cause the app using obfuscator dart code
